services:
  - type: web
    name: pdf-extraction-backend
    env: docker
    repo: https://github.com/Amit-TheOne/pdf-extraction
    rootDir: backend
    region: oregon
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CLIENT_URL
        sync: false
    dockerfilePath: backend/Dockerfile
